# Generated by Django 3.2.9 on 2021-11-16 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hawkers_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hawker',
            name='ClosingTime',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hawker',
            name='OpeningTime',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
