# Generated by Django 3.2.9 on 2021-11-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hawkers_app', '0002_auto_20211116_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hawker',
            name='AmIOpen',
            field=models.BooleanField(default=True),
        ),
    ]
